### ISSUE TITLE
Add option to use IAM roles instead of AK/SK

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#14]
First of all, thanks for the plugin! Works very well.

I am hosting my Jenkins server on an ec2 instance, like probably most of the people that will use this plugin. I think it would be great to leverage the IAM role assigned to the Jenkins EC2 instance to allow the plugin to deploy AWS Lambda functions.

The S3 Plugin for example, allows u to use IAM Roles. It's just a simple checkbox which will hide the Access Key and Secret Key input boxes.

**Comment by cast** [comment]
Hi Sam, 

Thanks for the feedback!

I'll definitely take this as a feature request. We use the plugin on a managed Jenkins so we didn't get to this yet.

**Comment by cast** [comment]
In the next version 0.2.5 the checkbox is added (doesn't hide the fields yet though).

It uses the DefaultAWSCredentialsProviderChain, so it will take in account in the given order:
- Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_KEY(_ID)
- Java System Properties - aws.accessKeyId and aws.secretKey
- Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
- Instance profile credentials delivered through the Amazon EC2 metadata service

It'll be available tomorrow through the update center.

**Comment by SamVerschueren** [comment]
Hi Michael

Thank you very much! Works like a charm.

Some minor remarks that can be fixed in the future (will create a new issue for these)
1. Remove the fields if checkbox is checked (as you mentioned yourself)
2. Do not show errors on the AK/SK fields if the checkbox is checked (but will probably be the case automatically if 1 is implemented)

Thanks again!
Sam
