### ISSUE TITLE
Remove AK/SK field if "Instance Credentials" checkbox is checked

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#16]
As mentioned in https://github.com/XT-i/aws-lambda-jenkins-plugin/issues/14

1. Remove the fields if checkbox is checked
2. Do not show errors on the AK/SK fields if the checkbox is checked (but will probably be the case automatically if 1 is implemented)

**Comment by cast** [comment]
This was added in the 0.3.0 version yesterday. It required a custom jelly tag with a separate negative attribute for opening the block when not checked. In the regular optional block the checkbox negative attribute is used for both value and toggling, while only the toggling is needed.

**Comment by SamVerschueren** [comment]
Nice, thank you very much! 

Not very familiar with developing Jenkins plugins. But glad you have solved it ;).
