### ISSUE TITLE
Add possibility for using environment variables for Memory and Timeout

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#20]
Hi @cast 

I was wondering if it would be possible to use environment variables for the Memory and Timeout field. I guess this isn't currently possible because they are numeric?

Sam

**Comment by cast** [comment]
Hi Sam,

Those parameters are indeed not yet expandable using environment variables. I'll check if I can refactor them without data loss.
I can then just handle them as string and parse them in the end.

Thanks,

Michael

**Comment by SamVerschueren** [comment]
Would be awesome! I want to set the memory and timeout dynamically depending on branch (master, staging, ...).

**Comment by cast** [comment]
Added possibility to expand environment variables for timeout and memory in 0.3.1.
Should be visible in the update manager by tomorrow.

See you at the Thursday meetup btw ;)

**Comment by SamVerschueren** [comment]
Thank you very much for the fast release!

Haha, see you there ;)!

**Comment by SamVerschueren** [comment]
Just letting you know, works like a charm!
