### ISSUE TITLE
Please add flag for publishing a new version

### ISSUE THREAD

**Issue by jeffjen** [XT-i/aws-lambda-jenkins-plugin#23]
AWS lambda supports versioning now.

Please make it available so we could publish a new version for each build.

**Comment by cast** [comment]
Added publish version on master branch option

Optionally you can create or update an alias to the published version. Replicates $Latest behaviour if you want to use specifically numbered versions.

Still need to add documentation and additional unit tests.

**Comment by cast** [comment]
Publish version/Attach Alias/Event Sources support is available on release 0.3.2. This should be available tomorrow through the Jenkins plugin update panel.
