### ISSUE TITLE
Publish new version depending on environment variable

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#29]
I have no idea if this is possible, but I will explain my use case.

I have two git branches (`development`/`production`). The development branch is the `$LATEST` version as it is used for testing etc. When I push to production, it should create a new version and tag it as `production`. If pushed to `development`, it should just update the `$LATEST` but don't create a version or tag the release.

So actually what I need is an optional "create version + tag" depending on an environment variable that I can set depending on the branch pushed to. Any idea if this would be possible to do?

**Comment by cast** [comment]
Hi Sam,

I would suggest using the "conditional build step" plugin if you only want to make one job:

https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin

**Comment by SamVerschueren** [comment]
Aha, that might do the trick :). Thanks @cast!
