### ISSUE TITLE
Version + Alias created before update configuration

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#30]
I noticed that the version and alias are created before the configuration is updated. Is this expected behaviour?

**Comment by cast** [comment]
Accepting the issue, this is not good behaviour because the configuration change won't be included in the published lambda function

**Comment by cast** [comment]
Fixed in release 0.3.3

**Comment by SamVerschueren** [comment]
Thanks!
