### ISSUE TITLE
Separate build step for version + alias

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#31]
I was thinking that it would be nice to have a separate step for creating a version and alias. I think it offers more flexibility.

1. Update code and configuration
2. Create alias for $LATEST (no new version is created)
3. Create new version and alias the version (option to provide multiple aliases, maybe comma separated)

It would make conditionally applying versions and aliases a lot more easier.

How could this be integraded UI-wise? Leave it open to you but this is my suggestion.

1. An input box for the region
2. An input box for the lambda function
3. Two checkboxes, one for `Publish version` and on for `Assign Alias`. Both can be checked or unchecked independently. If `Assign Alias` is checked, an input box popups up for creating the alias(es).

If `Publish version` and `Assign Alias` are both checked, a new version is created which will be aliased by all the aliases provided in the input box (comma separated).

If only `Assign Alias` is checked, the aliases will be applied to the $LATEST version.

Feedback is more then welcome :).

**Comment by msulland** [comment]
Hi,

We are in need of a similar feature, having a separate publish version step in our pipeline. Something like "AWS Lambda Publish Version" with version and alias as input enabling the publishing of a new version and updating an alias to point to it.

**Comment by msulland** [comment]
I have now startet to look at the possibility to add this to the code.

**Comment by msulland** [comment]
Hi, I have now completed the code extension and are putting the finishing touches on it.

**Comment by cast** [comment]
Thanks msulland, I reviewed the pull request and merged it to this fork.
I will soon merge in the changes on the jenkinsci fork.

**Comment by cast** [comment]
Included in release 0.5.4, arriving during the course of tomorrow in update panel.

**Comment by SamVerschueren** [comment]
Great work guys! Thanks for doing this!
