### ISSUE TITLE
Support connecting to amazon through proxy

### ISSUE THREAD

**Issue by purpleD17** [XT-i/aws-lambda-jenkins-plugin#42]
I tried setting the java opts proxyHost and proxyPort using https and http, but neither worked. Perhaps the jenkins proxy needs to be loaded like this:

https://github.com/jenkinsci/stashnotifier-plugin/pull/12/commits/5db2af49eb54082680847b980413907e207b2230

Thanks.

**Comment by purpleD17** [comment]
I actually got the proxyHost and proxyPort to work, it had to be https.proxyHost and https.proxyPort.

However, i'd love this feature to become available so we don't have to do this. Thanks a lot. Perhaps one day I can try it myself, but until then if someone would like to implement this feature I would love it.

**Comment by cast** [comment]
Hi @purpleD17,

I'm giving this issue a wontfix label due to being out of scope for now.

**Comment by cast** [comment]
removing wontfix label, planning next release in a couple of days.

**Comment by cast** [comment]
Feature added in release 0.5.5
