### ISSUE TITLE
Configuration update does not update runtime

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#43]
With the new `nodejs4.3` runtime I looked into updating all the runtimes to 4.3. I just changed my jenkins configuration and deployed my code again. It seems that the runtime isn't updated.

> Lambda update configuration request:
{FunctionName: fnName,Role: arn:aws:iam::123456789012:role/lambda_role,Handler: index.handler,Description: test,Timeout: 10,MemorySize: 128,}

It seems [these](https://github.com/XT-i/aws-lambda-jenkins-plugin/blob/master/src/main/java/com/xti/jenkins/plugin/awslambda/service/LambdaDeployService.java#L254-L260) lines are the reason why it doesn't work. It does net set the runtime.

Will do a PR.

**Comment by cast** [comment]
Can't merge this onto the main fork due to this being impossible with the java sdk.

Will revert back to old on this branch.

Temporary fallback: manually update version in AWS console, or delete and recreate function.

Not supported by AWS java sdk

**Comment by SamVerschueren** [comment]
Wow, that's very odd... My bad, didn't checked it.

**Comment by SamVerschueren** [comment]
Is it possible to reopen this just to keep track of the issue? Created an issue in the java SDK repo. https://github.com/aws/aws-sdk-java/issues/684

**Comment by cast** [comment]
the new release of the java sdk (1.10.68) has runtime support for updatefunctionconfiguration. I will update the dependency and the functionality.

**Comment by cast** [comment]
Fixed in release 0.5.2.

**Comment by SamVerschueren** [comment]
It seems the documentation is a little bit behind then :). Thanks for looking into this @cast!
