### ISSUE TITLE
subnets and security group

### ISSUE THREAD

**Issue by mirkods** [XT-i/aws-lambda-jenkins-plugin#47]
Hi there,
I'm trying to upload a lambda function with VPC access through Jenkins.
I saw that you updated this awesome plugin in order to select subnets and security group but I have a question: which should be the input of the two fields?

I tried with the format `subnet-XXXXXXX` or only `XXXXXXX` but don't seem to work.

Cheers
Mirko

**Comment by cast** [comment]
Hi Mirko,

Could you check for any error in the console log?

Do you have the adequate policies with the user/role that you use for deployment?
 ec2 DescribeSubnets, DescribeSecurityGroups and DescribeVpcs?

I have an example configuration in the image below with a single subnet and security group, but you can use a comma separated list to add additional subnets and security groups.

![clipboard01](https://cloud.githubusercontent.com/assets/770930/15230690/4574d858-1897-11e6-891e-5af9dfcad199.jpg)

**Comment by mirkods** [comment]
Hi,
thanks for your response.
It was a role issue so I solved it. 

Thanks
Mirko
