### ISSUE TITLE
Support Role Based Authentication

### ISSUE THREAD

**Issue by stephenthoen1** [XT-i/aws-lambda-jenkins-plugin#48]
Hi! Great plugin, however it does not support the ability to support authentication through IAM roles.  It requires the secret key and access key instead.

**Comment by cast** [comment]
When checking the "use instance credentials" checkbox this should work without further configuration provided you are running it on ec2 instance and/or can access the instance metadata.

**Comment by bedge** [comment]
Docs need to be updated. 

https://github.com/XT-i/aws-lambda-jenkins-plugin#iam-setup says:

> The AWS Access Key Id, AWS Secret Key, region and function name are always required. All other fields depend on the update mode.
