### ISSUE TITLE
Java Heap Space error when deploying lambda function

### ISSUE THREAD

**Issue by aaron-kumar** [XT-i/aws-lambda-jenkins-plugin#50]
I am getting below error while deploying lambda function using AWS lambda plugin. I am specifying artifacts location inside as jenkins "target" directory instead of S3 location.

Stacktrace:
15:29:46 {FunctionName: my_lambda,Runtime: java8,Role: LambdaExecutionRole,Handler: com.mycompany.MyHandler::starter,Code: {ZipFile: java.nio.HeapByteBuffer[pos=0 lim=40959835 cap=40959835],},Description: Deployed with AWS lambda Plugin :7,Timeout: 40,MemorySize: 384,Publish: false,}
15:29:46 
15:29:46 com.amazonaws.AmazonClientException: Unable to marshall request to JSON: Java heap space
15:29:46 	at com.amazonaws.services.lambda.model.transform.CreateFunctionRequestMarshaller.marshall(CreateFunctionRequestMarshaller.java:191)
15:29:46 	at com.amazonaws.services.lambda.AWSLambdaClient.createFunction(AWSLambdaClient.java:703)
15:29:46 	at com.xti.jenkins.plugin.awslambda.service.LambdaDeployService.createLambdaFunction(LambdaDeployService.java:171)
15:29:46 	at com.xti.jenkins.plugin.awslambda.service.LambdaDeployService.deployLambda(LambdaDeployService.java:83)
15:29:46 	at com.xti.jenkins.plugin.awslambda.upload.LambdaUploader.upload(LambdaUploader.java:51)
15:29:46 	at com.xti.jenkins.plugin.awslambda.callable.DeployCallable.call(DeployCallable.java:46)
15:29:46 	at com.xti.jenkins.plugin.awslambda.callable.DeployCallable.call(DeployCallable.java:23)
15:29:46 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
15:29:46 	at com.xti.jenkins.plugin.awslambda.upload.LambdaUploadPublisher.perform(LambdaUploadPublisher.java:93)
15:29:46 	at com.xti.jenkins.plugin.awslambda.upload.LambdaUploadPublisher.perform(LambdaUploadPublisher.java:69)
15:29:46 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
15:29:46 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
15:29:46 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
15:29:46 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
15:29:46 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
15:29:46 	at hudson.model.Run.execute(Run.java:1766)
15:29:46 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
15:29:46 	at hudson.model.ResourceController.execute(ResourceController.java:98)
15:29:46 	at hudson.model.Executor.run(Executor.java:410)
15:29:46 Caused by: java.lang.OutOfMemoryError: Java heap space
15:29:46 	at javax.xml.bind.DatatypeConverterImpl._printBase64Binary(Unknown Source)
15:29:46 	at javax.xml.bind.DatatypeConverterImpl._printBase64Binary(Unknown Source)
15:29:46 	at javax.xml.bind.DatatypeConverterImpl.printBase64Binary(Unknown Source)
15:29:46 	at javax.xml.bind.DatatypeConverter.printBase64Binary(Unknown Source)
15:29:46 	at com.amazonaws.util.Base64.encodeAsString(Base64.java:39)
15:29:46 	at com.amazonaws.util.BinaryUtils.toBase64(BinaryUtils.java:59)
15:29:46 	at com.amazonaws.util.json.JSONWriter.value(JSONWriter.java:347)
15:29:46 	at com.amazonaws.services.lambda.model.transform.CreateFunctionRequestMarshaller.marshall(CreateFunctionRequestMarshaller.java:122)
15:29:46 	... 18 more

**Comment by aaron-kumar** [comment]
I face this issue when I tried to upload artifacts (of approx. 40MB) through Jenkins. But when I placed artifact in S3 bucket, everything work fine. That means, there is problem in uploading artifacts (zip/jar) of large size from Jenkins workspace directory

**Comment by rayhogenson** [comment]
I, too, am affected by this issue.

**Comment by cast** [comment]
For files larger than 10 MB, consider uploading via S3. (from AWS console)

You can then use the following artifact location:
s3://bucket/key or s3://bucket/key?versionId=versionId

This should fix your issue right now, since it is caused by memory settings in combination with the AWS Java SDK.

I might consider direct upload of the file to S3 as an option in the future.
