### ISSUE TITLE
Zipfile not found 

### ISSUE THREAD

**Issue by ranlandau** [XT-i/aws-lambda-jenkins-plugin#51]
Hi,

I'm trying to use this plugin to update my Lambda function.

2 Questions:

1. Code is retreived from git,
   and when running the build script i get
   Could not find zipfile or folder.
  
  What should i input in the file location to make it work?

2. How can i run pip install before and add some libs to my zip prior to upload?

Thanks!

**Comment by cast** [comment]
Hi Ranlandau.

Closing due to unrelated to plugin.

Please check jenkins and available plugin documentation. 
Using a shell build step is a simple way to solve your need to install libraries.
