### ISSUE TITLE
SubnetIds and SecurityIds must coexist or be both empty lists

### ISSUE THREAD

**Issue by SamVerschueren** [XT-i/aws-lambda-jenkins-plugin#56]
Since about 30 minutes I started receiving these errors when Jenkins tries to deploy my build.

> com.amazonaws.services.lambda.model.InvalidParameterValueException: SubnetIds and SecurityIds must coexist or be both empty list. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: b17cab79-d3f3-11e6-9bee-e7fb56d0a4ae)

I checked the documentation and I believe this has something to do with the [VpcConfig parameter inside createFunction](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property). I used the JavaScript docs to check that because the Java docs doesn't work for me :p. They aren't marked as `required` yet but probably they changed that which is odd IMO.

**Comment by cast** [comment]
@SamVerschueren pull request https://github.com/jenkinsci/aws-lambda-plugin/pull/11 by @CiliaFred provides relief. Release 0.5.8 performed, should be available in download center tomorrow.

**Comment by SamVerschueren** [comment]
Oh sweet! Thanks @cast! Just wondering, what is the relationship between that repository and this one? Why was the PR filed on that fork instead of directly on this one?
