### ISSUE TITLE
Jenkins pipeline support

### ISSUE THREAD

**Issue by ajohnstone** [XT-i/aws-lambda-jenkins-plugin#58]
Does this plugin support pipelines/workflows via Jenkinsfile?

**Comment by mario-mazo** [comment]
+1

**Comment by robincsmith** [comment]
+1

**Comment by cast** [comment]
Hi @ajohnstone 

The plugin supports pipeline and can be used by the pipeline syntax generator.
The following short form names will arrive with update 0.5.9: deployLambda, invokeLambda, publishLambda and eventSourceLambda

**Comment by SamVerschueren** [comment]
Where can I find the pipeline syntax generator? Is it a online tool? Is it built-in into Jenkins? I really want to use this with pipelines but not sure about the syntax.

**Comment by robincsmith** [comment]
There’s a Snippet Generator - it should be available through your Jenkins instance: <your Jenkins server>/pipeline-syntax/

If you go to the landing page of any of your pipeline jobs, the link should appear on the left-hand side of the page, under ‘Pipeline Syntax'

**Comment by SamVerschueren** [comment]
Nice!!!!! Thanks!

**Comment by tstibbs** [comment]
It's a shame this has been closed without any docs. To use the snippet generator I have to first install the plugin - it would be really useful to have a couple of examples of the syntax so I can see if it meets my needs before going to the effort to install.

**Comment by sjelison** [comment]
I'm trying to figure out how to configure a proxy when using deployLambda in a pipeline.  Any hints or help?
