### ISSUE TITLE
Is the temporary zip file ever cleaned up?

### ISSUE THREAD

**Issue by yegeniy** [XT-i/aws-lambda-jenkins-plugin#70]
It seems that after the zip file is upload, there's no need to keep the temp file around and we could delete it, or provide an option to delete it.
Some jenkins installations use a temp folder that is actually not cleaned up automatically. Usually this is not an issue, but the temp file generated by this plugin can easily be dozens of MBs in size.

**Comment by cast** [comment]
The current behaviour of the plugin is to temporarily load the file into memory and delete the temporary file. If this fails for some reason this is not fatal but the logs should contain the following text: "Could not delete temporary file: temp-file"

Could you provide more information of the problem you are seeing with the temp file and post a redacted log file?

**Comment by yegeniy** [comment]
I just got saw this notification now. Sorry about the delay :p 
Closing due to age.
